name: Endor Labs - Python SCA Scan on PR
on:
  workflow_dispatch
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements/requirements.txt
            
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            enable_github_action_token: true
            scan_dependencies: true
            pr: true
            pr_baseline: main # develop, etc
            additional_args: "--pr-incremental --include-path=requirements/**" # Additional parameters can be passed with whitespace separation, for example: --github to enable RSPM
            enable_pr_comments: true # <-- Uncomment to enable PR comments if enabled comment out pr_baseline
            github_token: ${{ secrets.GH_TOKEN }} # needs to be enabled if you want to use enable_pr_comments
            scan_secrets: true # <-- Uncomment to enable secrets scanning
            scan_git_logs: true # <-- Uncomment to scan git logs for committed secrets
            scan_github_actions: true # <-- Uncomment to scan GH Action Vulnerabilities
            scan_tools: true # <-- Uncomment to scan identified tools
            tags: "actor = ${{ github.actor }},run-id = ${{ github.run_id }},event name = ${{ github.event_name }},workflow = ${{ github.workflow }},github sha = ${{ github.sha }}"
